### ISSUE TITLE
www.crifan.com 这个网站打不开了

### ISSUE THREAD

**Issue by Leser2020** [crifan/crifan_ebook_readme#4]
www.crifan.com 这个网站打不开了

**Comment by crifan** [comment]
之前的 www.crifan.com 被封了 -》麻烦把 www.crifan.com 改为 www.crifan.org 即可，谢谢。

**Comment by Karmylr** [comment]
@crifan book.crifan.org 打不开了

**Comment by crifan** [comment]
> [@crifan](https://github.com/crifan) book.crifan.org 打不开了

直接打开
https://book.crifan.org
是（故意的，限制权限，而）打不开的；

但是直接打开其下目录中的内容，是可以打开的

比如某个电子书教程的首页地址
https://book.crifan.org/books/mobile_re_capture_bypass_limit/website/
是可以打开的

**Comment by Karmylr** [comment]
@crifan 
https://book.crifan.org/books/mobile_re_capture_bypass_limit/website/ 还是不行唉
<img width="962" height="663" alt="Image" src="https://github.com/user-attachments/assets/53678481-58b6-47ff-8a1d-938988cb0d44" />

**Comment by crifan** [comment]
> [@crifan](https://github.com/crifan) https://book.crifan.org/books/mobile_re_capture_bypass_limit/website/ 还是不行唉 <img alt="Image" width="962" height="663" src="https://private-user-images.githubusercontent.com/69903376/464115990-53678481-58b6-47ff-8a1d-938988cb0d44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTI0ODc3NjYsIm5iZiI6MTc1MjQ4NzQ2NiwicGF0aCI6Ii82OTkwMzM3Ni80NjQxMTU5OTAtNTM2Nzg0ODEtNThiNi00N2ZmLThhMWQtOTM4OTg4Y2IwZDQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzE0VDEwMDQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxOTE2NjFhNGVmMzNlNzU2YjM5ZWFlOGZiZGZjNzk4ZmNhOWZhZDU0ZTY1MjdjZGZmYjY3MTI4MDcxYTg3OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CXZ9L7JGFhh50KkeZtZmDlZbS3V0swqhPsabtvYkeWY">

我这里是可以的啊：
https://book.crifan.org/books/mobile_re_capture_bypass_limit/website/

<img width="1871" height="1055" alt="Image" src="https://github.com/user-attachments/assets/b0629d94-2f03-4c84-acd4-8ccbff28e8eb" />

如果还不行，那你加上代理=翻墙，再试，应该就可以了。

注：crifan.org这个网址，按理说，中国多数地方的IP，都不需要代理即可正常打开；可能有部分地区特殊，需要加上翻墙代理才能打开
